version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

python:
  system_packages: true
  install:
    - requirements: requirements-doc.txt
    - method: pip
      path: .

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
